export const EDUCATION_LEVELS = [
  "No Formal Education",
  "Primary (KCPE)",
  "Form Four (KCSE)",
  "Certificate",
  "Diploma",
  "Higher Diploma",
  "Bachelor's Degree",
  "Master's Degree",
  "PhD / Doctorate",
];

export const MARITAL_STATUSES = [
  "Single",
  "Married",
  "Divorced",
  "Separated",
  "Widowed",
];

export const RELIGIONS = [
  "Christian",
  "Muslim",
  "Hindu",
  "Traditional African Religion",
  "Atheist / Agnostic",
  "Buddhist",
  "Sikh",
];

// Major Kenyan ethnic communities. Not exhaustive (there are 40+ recognized
// communities) -- falls back to "Other" for anything not listed.
export const ETHNICITIES = [
  "Kikuyu",
  "Luhya",
  "Luo",
  "Kalenjin",
  "Kamba",
  "Kisii",
  "Meru",
  "Mijikenda",
  "Maasai",
  "Turkana",
  "Embu",
  "Taita",
  "Kuria",
  "Somali",
  "Samburu",
  "Pokot",
  "Teso",
  "Tharaka",
  "Borana",
  "Rendille",
  "Orma",
  "Gabra",
  "Sabaot",
  "Swahili",
  "Nubian",
  "Kenyan Arab",
];

// Common occupations. Not exhaustive -- falls back to "Other" for anything
// not listed.
export const PROFESSIONS = [
  "Accountant",
  "Actor / Actress",
  "Architect",
  "Artist",
  "Banker",
  "Business Owner / Entrepreneur",
  "Chef",
  "Civil Servant",
  "Consultant",
  "Customer Service",
  "Dentist",
  "Doctor / Medical Professional",
  "Driver",
  "Electrician",
  "Engineer",
  "Farmer",
  "Fashion Designer",
  "Hair Stylist / Beautician",
  "Human Resources",
  "IT / Software Developer",
  "Journalist / Media",
  "Lawyer",
  "Lecturer / Professor",
  "Marketing",
  "Mechanic",
  "Musician",
  "Nurse",
  "Pastor / Religious Leader",
  "Photographer",
  "Pilot",
  "Plumber",
  "Police / Military",
  "Real Estate",
  "Sales",
  "Scientist / Researcher",
  "Social Worker",
  "Student",
  "Tailor / Fashion",
  "Teacher",
  "Trader / Business",
  "Unemployed",
];
