// Major towns per county, keyed by the exact county names in ./counties.js.
// Not exhaustive (Kenya has far more towns/estates than fit here) — the
// registration form falls back to a free-text "Other" option for towns not
// listed.
export const TOWNS_BY_COUNTY = {
  "Baringo": ["Kabarnet", "Eldama Ravine", "Marigat", "Mogotio", "Kabartonjo"],
  "Bomet": ["Bomet", "Sotik", "Longisa", "Chepalungu", "Mulot"],
  "Bungoma": ["Bungoma", "Webuye", "Kimilili", "Chwele", "Kanduyi"],
  "Busia": ["Busia", "Malaba", "Nambale", "Funyula", "Port Victoria"],
  "Elgeyo Marakwet": ["Iten", "Kapsowar", "Chepkorio", "Kapcherop", "Tambach"],
  "Embu": ["Embu", "Runyenjes", "Siakago", "Manyatta", "Kiritiri"],
  "Garissa": ["Garissa", "Dadaab", "Hulugho", "Fafi", "Balambala"],
  "Homa Bay": ["Homa Bay", "Kendu Bay", "Mbita", "Oyugis", "Rangwe"],
  "Isiolo": ["Isiolo", "Merti", "Garbatulla", "Kinna"],
  "Kajiado": ["Kajiado", "Ngong", "Kitengela", "Namanga", "Isinya"],
  "Kakamega": ["Kakamega", "Mumias", "Malava", "Butere", "Lugari"],
  "Kericho": ["Kericho", "Litein", "Kipkelion", "Sosiot", "Ainamoi"],
  "Kiambu": ["Kiambu", "Thika", "Ruiru", "Limuru", "Kikuyu"],
  "Kilifi": ["Kilifi", "Malindi", "Watamu", "Mtwapa", "Mariakani"],
  "Kirinyaga": ["Kerugoya", "Kutus", "Sagana", "Baricho", "Wanguru"],
  "Kisii": ["Kisii", "Ogembo", "Suneka", "Nyamache", "Keroka"],
  "Kisumu": ["Kisumu", "Maseno", "Ahero", "Muhoroni", "Nyahera"],
  "Kitui": ["Kitui", "Mwingi", "Mutomo", "Kabati", "Zombe"],
  "Kwale": ["Kwale", "Ukunda", "Msambweni", "Diani", "Lunga Lunga"],
  "Laikipia": ["Nanyuki", "Nyahururu", "Rumuruti", "Sipili"],
  "Lamu": ["Lamu", "Mpeketoni", "Witu", "Faza"],
  "Machakos": ["Machakos", "Athi River", "Kangundo", "Matuu", "Mwala"],
  "Makueni": ["Wote", "Sultan Hamud", "Emali", "Kibwezi", "Makindu"],
  "Mandera": ["Mandera", "Rhamu", "El Wak", "Takaba"],
  "Marsabit": ["Marsabit", "Moyale", "Loiyangalani", "North Horr"],
  "Meru": ["Meru", "Nkubu", "Maua", "Timau", "Mikinduri"],
  "Migori": ["Migori", "Rongo", "Awendo", "Isebania", "Kehancha"],
  "Mombasa": ["Mombasa", "Likoni", "Nyali", "Kisauni", "Changamwe"],
  "Murang'a": ["Murang'a", "Kenol", "Kangema", "Kandara", "Kigumo"],
  "Nairobi": ["Nairobi CBD", "Westlands", "Kasarani", "Embakasi", "Kibra", "Dagoretti"],
  "Nakuru": ["Nakuru", "Naivasha", "Molo", "Gilgil", "Njoro"],
  "Nandi": ["Kapsabet", "Nandi Hills", "Mosoriot", "Kabiyet"],
  "Narok": ["Narok", "Kilgoris", "Ololulunga", "Suswa"],
  "Nyamira": ["Nyamira", "Nyansiongo", "Ekerenyo", "Manga"],
  "Nyandarua": ["Ol Kalou", "Njabini", "Engineer", "Ol Joro Orok"],
  "Nyeri": ["Nyeri", "Karatina", "Othaya", "Mukurweini", "Naro Moru"],
  "Samburu": ["Maralal", "Baragoi", "Wamba", "Archer's Post"],
  "Siaya": ["Siaya", "Bondo", "Ugunja", "Yala", "Usenge"],
  "Taita Taveta": ["Voi", "Taveta", "Mwatate", "Wundanyi"],
  "Tana River": ["Hola", "Garsen", "Bura", "Madogo"],
  "Tharaka Nithi": ["Chuka", "Marimanti", "Kathwana", "Chogoria"],
  "Trans Nzoia": ["Kitale", "Endebess", "Kiminini", "Cherangany"],
  "Turkana": ["Lodwar", "Lokichogio", "Kakuma", "Lokitaung"],
  "Uasin Gishu": ["Eldoret", "Burnt Forest", "Moiben", "Turbo"],
  "Vihiga": ["Mbale", "Luanda", "Chavakali", "Majengo"],
  "Wajir": ["Wajir", "Habaswein", "Griftu", "Bute"],
  "West Pokot": ["Kapenguria", "Chepareria", "Sigor", "Kacheliba"],
};
